### ISSUE TITLE
Installation fails on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by edap** [phonegap/ios-deploy#178]
Running `npm install -g ios-deploy` reports this error:

```bash
npm install ios-deploy -g
\
> ios-deploy@1.7.0 preinstall /usr/local/lib/node_modules/ios-deploy
> make ios-deploy

gcc -ObjC -g -o ios-deploy -framework Foundation -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks ios-deploy.c
In file included from ios-deploy.c:4:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:6:
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
@class NSArray<ObjectType>;
              ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:16: error: cannot find protocol declaration for 'ObjectType'
@class NSArray<ObjectType>;
               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:25: error: cannot find protocol declaration for 'ObjectType'
@interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                        ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:37: error: expected identifier or '('
@interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
                                    ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:13: error: expected ')'
- (nullable ObjectType)nextObject;
            ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:36:3: note: to match this '('
- (nullable ObjectType)nextObject;
  ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:25: error: cannot find protocol declaration for 'ObjectType'
@interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                        ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:1: error: duplicate interface definition for class 'NSEnumerator'
@interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:34:12: note: previous definition is here
@interface NSEnumerator<ObjectType> : NSObject <NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:37: error: method type specifier must start with '-' or '+'
@interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                    ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:40:38: error: expected a type
@interface NSEnumerator<ObjectType> (NSExtendedEnumerator)
                                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:1: error: expected selector for Objective-C method
@property (readonly, copy) NSArray<ObjectType> *allObjects;
^
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:42:36: error: cannot find protocol declaration for 'ObjectType'
@property (readonly, copy) NSArray<ObjectType> *allObjects;
                                   ^
In file included from ios-deploy.c:4:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:32: error: cannot find protocol declaration for 'ObjectType'
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:44: error: expected identifier or '('
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
                                           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:19:4: error: expected a type
- (ObjectType)objectAtIndex:(NSUInteger)index;
   ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:40: error: expected ')'
- (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                       ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:21:33: note: to match this '('
- (instancetype)initWithObjects:(const ObjectType [])objects count:(NSUInteger)cnt NS_DESIGNATED_INITIALIZER;
                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:20: error: cannot find protocol declaration for 'ObjectType'
@interface NSArray<ObjectType> (NSExtendedArray)
                   ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:1: error: duplicate interface definition for class 'NSArray'


  1 0 info it worked if it ends with ok
@interface NSArray<ObjectType> (NSExtendedArray)
^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
@interface NSArray<ObjectType> (NSExtendedArray)
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [ios-deploy] Error 1
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! ios-deploy@1.7.0 preinstall: `make ios-deploy`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ios-deploy@1.7.0 preinstall script 'make ios-deploy'.
npm ERR! This is most likely a problem with the ios-deploy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make ios-deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-deploy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/da1/Sources/cognita/reader-cordova/npm-debug.log
```

I think that this can somehow be related with the new mac policies about the /usr/bin folder linking, but I'm not sure. I can not upload the error log, i've to copy&paste it here.

```bash
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-deploy' ]
2 info using npm@2.11.2
3 info using node@v0.12.5
4 verbose node symlink /usr/local/bin/node
5 verbose install initial load of /usr/local/lib/package.json
6 verbose readDependencies loading dependencies from /usr/local/lib/package.json
7 silly cache add args [ 'ios-deploy', null ]
8 verbose cache add spec ios-deploy
9 silly cache add parsed spec { raw: 'ios-deploy',
9 silly cache add   scope: null,
9 silly cache add   name: 'ios-deploy',
9 silly cache add   rawSpec: '',
9 silly cache add   spec: '*',
9 silly cache add   type: 'range' }
10 silly addNamed ios-deploy@*
11 verbose addNamed "*" is a valid semver range for ios-deploy
12 silly addNameRange { name: 'ios-deploy', range: '*', hasData: false }
13 silly mapToRegistry name ios-deploy
14 silly mapToRegistry using default registry
15 silly mapToRegistry registry https://registry.npmjs.org/
16 silly mapToRegistry uri https://registry.npmjs.org/ios-deploy
17 verbose addNameRange registry:https://registry.npmjs.org/ios-deploy not in flight; fetching
18 verbose request uri https://registry.npmjs.org/ios-deploy
19 verbose request no auth needed
20 info attempt registry request try #1 at 13:49:31
21 verbose request id 830058556880681f
22 verbose etag "4ZU8WR1DBHVI68KV8FITWX1LI"
23 http request GET https://registry.npmjs.org/ios-deploy
24 http 304 https://registry.npmjs.org/ios-deploy
25 silly get cb [ 304,
25 silly get   { date: 'Mon, 05 Oct 2015 11:49:31 GMT',
25 silly get     via: '1.1 varnish',
25 silly get     'cache-control': 'max-age=60',
25 silly get     etag: '"4ZU8WR1DBHVI68KV8FITWX1LI"',
25 silly get     age: '0',
25 silly get     connection: 'keep-alive',
25 silly get     'x-served-by': 'cache-lhr6332-LHR',
25 silly get     'x-cache': 'HIT',
25 silly get     'x-cache-hits': '1',
25 silly get     'x-timer': 'S1444045771.589471,VS0,VE156',
25 silly get     vary: 'Accept' } ]
26 verbose etag https://registry.npmjs.org/ios-deploy from cache
27 verbose get saving ios-deploy to /Users/da1/.npm/registry.npmjs.org/ios-deploy/.cache.json
28 silly addNameRange number 2 { name: 'ios-deploy', range: '*', hasData: true }
29 silly addNameRange versions [ 'ios-deploy',
29 silly addNameRange   [ '1.0.1',
29 silly addNameRange     '1.0.2',
29 silly addNameRange     '1.0.3',
29 silly addNameRange     '1.0.4',
29 silly addNameRange     '1.0.5',
29 silly addNameRange     '1.0.6',
29 silly addNameRange     '1.0.7',
29 silly addNameRange     '1.0.8',
29 silly addNameRange     '1.0.9',
29 silly addNameRange     '1.1.0',
29 silly addNameRange     '1.2.0',
29 silly addNameRange     '1.3.0',
29 silly addNameRange     '1.3.1',
29 silly addNameRange     '1.3.2',
29 silly addNameRange     '1.4.0',
29 silly addNameRange     '1.5.0',
29 silly addNameRange     '1.6.0',
29 silly addNameRange     '1.6.1',
29 silly addNameRange     '1.6.2',
29 silly addNameRange     '1.6.3',
29 silly addNameRange     '1.7.0' ] ]
30 silly addNamed ios-deploy@1.7.0
31 verbose addNamed "1.7.0" is a plain semver version for ios-deploy
32 silly cache afterAdd ios-deploy@1.7.0
33 verbose afterAdd /Users/da1/.npm/ios-deploy/1.7.0/package/package.json not in flight; writing
34 verbose afterAdd /Users/da1/.npm/ios-deploy/1.7.0/package/package.json written
35 silly install resolved [ { name: 'ios-deploy',
35 silly install resolved     version: '1.7.0',
35 silly install resolved     os: [ 'darwin' ],
35 silly install resolved     description: 'launch iOS apps iOS devices from the command line (Xcode 6)',
35 silly install resolved     main: 'ios-deploy',
35 silly install resolved     scripts: { preinstall: 'make ios-deploy' },
35 silly install resolved     bin: { 'ios-deploy': './ios-deploy' },
35 silly install resolved     repository:
35 silly install resolved      { type: 'git',
35 silly install resolved        url: 'git+https://github.com/phonegap/ios-deploy.git' },
35 silly install resolved     keywords: [ 'ios-deploy', 'deploy to iOS device' ],
35 silly install resolved     author: { name: 'Greg Hughes' },
35 silly install resolved     license: 'GPLv3',
35 silly install resolved     gitHead: '6d61b7ca7c0ff16caea4e87a91ee7535db888621',
35 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-deploy/issues' },
35 silly install resolved     homepage: 'https://github.com/phonegap/ios-deploy#readme',
35 silly install resolved     _id: 'ios-deploy@1.7.0',
35 silly install resolved     _shasum: '8dfbce5c23ea74e77cb12870b2e72a3af8e1db91',
35 silly install resolved     _from: 'ios-deploy@*',
35 silly install resolved     _npmVersion: '2.9.1',
35 silly install resolved     _nodeVersion: '0.10.30',
35 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
35 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '8dfbce5c23ea74e77cb12870b2e72a3af8e1db91',
35 silly install resolved        tarball: 'http://registry.npmjs.org/ios-deploy/-/ios-deploy-1.7.0.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-deploy/-/ios-deploy-1.7.0.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install ios-deploy@1.7.0 into /usr/local/lib
37 info installOne ios-deploy@1.7.0
38 verbose installOne of ios-deploy to /usr/local/lib not in flight; installing
39 verbose lock using /Users/da1/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
40 silly install write writing ios-deploy 1.7.0 to /usr/local/lib/node_modules/ios-deploy
41 verbose unbuild lib/node_modules/ios-deploy
42 silly gentlyRm /usr/local/lib/node_modules/ios-deploy is being purged from base /usr/local
43 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-deploy
44 verbose tar unpack /Users/da1/.npm/ios-deploy/1.7.0/package.tgz
45 verbose tar unpacking to /usr/local/lib/node_modules/ios-deploy
46 silly gentlyRm /usr/local/lib/node_modules/ios-deploy is being purged
47 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-deploy
48 silly gunzTarPerm modes [ '755', '644' ]
49 silly gunzTarPerm extractEntry package.json
50 silly gunzTarPerm extractEntry .npmignore
51 silly gunzTarPerm extractEntry README.md
52 silly gunzTarPerm extractEntry LICENSE
53 silly gunzTarPerm extractEntry ResourceRules.plist
54 silly gunzTarPerm extractEntry Makefile
55 silly gunzTarPerm extractEntry MobileDevice.h
56 silly gunzTarPerm extractEntry CONTRIBUTING.md
57 silly gunzTarPerm extractEntry Info.plist
58 silly gunzTarPerm extractEntry demo.c
59 silly gunzTarPerm extractEntry errors.h
60 silly gunzTarPerm extractEntry ios-deploy.c
61 silly gunzTarPerm extractEntry Entitlements.plist
62 silly gunzTarPerm extractEntry resources/buildbox/build.sh
63 verbose write writing to /usr/local/lib/node_modules/ios-deploy/package.json
64 info preinstall ios-deploy@1.7.0
65 verbose unsafe-perm in lifecycle true
66 info ios-deploy@1.7.0 Failed to exec preinstall script
67 verbose unlock done using /Users/da1/.npm/_locks/ios-deploy-198957223cd98201.lock for /usr/local/lib/node_modules/ios-deploy
68 verbose stack Error: ios-deploy@1.7.0 preinstall: `make ios-deploy`
68 verbose stack Exit status 2
68 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
68 verbose stack     at EventEmitter.emit (events.js:110:17)
68 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
68 verbose stack     at ChildProcess.emit (events.js:110:17)
68 verbose stack     at maybeClose (child_process.js:1015:16)
68 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
69 verbose pkgid ios-deploy@1.7.0
70 verbose cwd /Users/da1/Sources/cognita/reader-cordova
71 error Darwin 15.0.0
72 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
73 error node v0.12.5
74 error npm  v2.11.2
75 error code ELIFECYCLE
76 error ios-deploy@1.7.0 preinstall: `make ios-deploy`
76 error Exit status 2
77 error Failed at the ios-deploy@1.7.0 preinstall script 'make ios-deploy'.
77 error This is most likely a problem with the ios-deploy package,
77 error not with npm itself.
77 error Tell the author that this fails on your system:
77 error     make ios-deploy
77 error You can get their info via:
77 error     npm owner ls ios-deploy
77 error There is likely additional logging output above.
78 verbose exit [ 1, true ]
79 verbose unbuild lib/node_modules/ios-deploy
80 info preuninstall ios-deploy@1.7.0
81 info uninstall ios-deploy@1.7.0
82 verbose unbuild rmStuff ios-deploy@1.7.0 from /usr/local/lib/node_modules
83 silly gentlyRm /usr/local/bin/ios-deploy is being gently removed
84 silly gentlyRm verifying /usr/local is an npm working directory
85 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
86 silly gentlyRm deletion target /usr/local/bin/ios-deploy is under /usr/local
87 verbose gentlyRm vacuuming from /usr/local/bin/ios-deploy up to /usr/local
88 info postuninstall ios-deploy@1.7.0
89 silly gentlyRm /usr/local/lib/node_modules/ios-deploy is being purged from base /usr/local
90 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-deploy
91 silly vacuum-fs purging /usr/local/lib/node_modules/ios-deploy
92 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules
```

**Comment by shazron** [comment]
Can you provide the info required here: https://github.com/phonegap/ios-deploy/blob/master/CONTRIBUTING.md ?

**Comment by shazron** [comment]
Try the new 1.8.0 release (will be up soon).

**Comment by e14pearle** [comment]
i had the same problem and this solved it http://stackoverflow.com/questions/21314132/npm-get-previous-versions-of-a-package - i.e. the part at the bottom 

npm config set registry http://registry.npmjs.org

**Comment by shazron** [comment]
Closing - see last issue for possible resolution? I can't repro this even with a vm. Re-open if you have more info for me.
