### ISSUE TITLE
ios-deploy fails to deploy to real device often

### ISSUE THREAD

**Issue by steinwelberg** [phonegap/ios-deploy#297]
When Appium 1.6.5 runs ios-deploy it sometimes fails. It's quite random when it fails and when it doesn't. Performing the command manually seems to never fails the install..

The ios-deploy command:
```ios-deploy --id 9fef44b142f29694091676fe6af8c31c8a4e34d5 --uninstall --bundle /var/folders/ft/5tpf22896634v2d5x88bcl500000gn/T/2017527-9489-uas5i8.ypa3piudi/Payload/OneginiExampleApp.app```

The error that is returned:
```
Error: Could not install app: 'Command 'ios-deploy --id 9fef44b142f29694091676fe6af8c31c8a4e34d5 --uninstall --bundle /var/folders/ft/5tpf22896634v2d5x88bcl500000gn/T/2017527-9489-uas5i8.ypa3piudi/Payload/OneginiExampleApp.app' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Could not install app: 'Command 'ios-deploy --id 9fef44b142f29694091676fe6af8c31c8a4e34d5 --uninstall --bundle /var/folders/ft/5tpf22896634v2d5x88bcl500000gn/T/2017527-9489-uas5i8.ypa3piudi/Payload/OneginiExampleApp.app' exited with code 253'
    at IOSDeploy.install$ (../../lib/ios-deploy.js:38:13)
    at tryCatch (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/avm/versions/1.6.5/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
# Expected behavior
I expect Appium to successfully install the app always.

# Actual behavior.
It randomly fails to install the app with the above error.

# Steps to reproduce the problem
I run my Appium test suite which reinstalls the app about 20-30 times for different test scenarios.

# System Specs

- [ ] 1. system_profiler SPSoftwareDataType
```
Software:

    System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Onegini’s Mac mini
      User Name: Onegini Administrator (administrator)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 7 days 17:04
```
- [ ] 2. ios-deploy -V
```
1.9.1
```
- [ ] 3. xcodebuild -version
```
Xcode 8.3.3
Build version 8E3004b
```
- [ ] 4. xcode-select --print-path
```
/Applications/Xcode.app/Contents/Developer
```
- [ ] 5. gcc --version
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
- [ ] 6. lldb --version
```
lldb-370.0.42
  Swift-3.1
```

**Comment by sharecommute** [comment]
I am facing this issue on ios 10+

**Comment by steinwelberg** [comment]
Same for me. The device that I'm trying to deploy to is running the latest iOS version atm (10.3.3).

**Comment by shazron** [comment]
See if the fix in #292 works for you

**Comment by steinwelberg** [comment]
It seems to work! :-).

**Comment by sharecommute** [comment]
@steinwelberg , can u please let me know how should i resolve this. I am getting the same error.

**Comment by steinwelberg** [comment]
Yes, I updated Appium to the latest beta version and that resolved the issue!
