### ISSUE TITLE
npm install permission denied

### ISSUE THREAD

**Issue by dpogue** [phonegap/ios-deploy#316]
Running `npm -g install ios-deploy` and getting a "Permission denied" error from check_reqs.js

# Expected behavior
ios-deploy should install successfully.

# Actual behavior.
```
> ios-deploy@1.9.2 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild

sh: ./src/scripts/check_reqs.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dpogue/.npm/_logs/2017-09-05T20_40_57_862Z-debug.log
```

<details>
<summary>Full npm debug log</summary>

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ios-deploy' ]
2 info using npm@5.4.0
3 info using node@v8.4.0
4 verbose npm-session 5346ca4b697f89d9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/ios-deploy 21ms (from cache)
8 silly pacote tag manifest for ios-deploy@latest fetched in 48ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule ios-deploy@1.9.2 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── ios-deploy@1.9.2
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add ios-deploy@1.9.2
19 silly decomposeActions action count 8
20 silly decomposeActions fetch ios-deploy@1.9.2
21 silly decomposeActions extract ios-deploy@1.9.2
22 silly decomposeActions preinstall ios-deploy@1.9.2
23 silly decomposeActions build ios-deploy@1.9.2
24 silly decomposeActions install ios-deploy@1.9.2
25 silly decomposeActions postinstall ios-deploy@1.9.2
26 silly decomposeActions finalize ios-deploy@1.9.2
27 silly decomposeActions refresh-package-json ios-deploy@1.9.2
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /Users/dpogue/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /Users/dpogue/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
32 silly doParallel extract 8
33 silly extract ios-deploy@1.9.2
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize /usr/local/lib/node_modules/ios-deploy
39 silly doParallel refresh-package-json 8
40 silly refresh-package-json /usr/local/lib/node_modules/ios-deploy
41 silly doParallel preinstall 8
42 silly preinstall ios-deploy@1.9.2
43 info lifecycle ios-deploy@1.9.2~preinstall: ios-deploy@1.9.2
44 verbose lifecycle ios-deploy@1.9.2~preinstall: unsafe-perm in lifecycle true
45 verbose lifecycle ios-deploy@1.9.2~preinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/ios-deploy/node_modules/.bin:/usr/local/lib/node_modules/.bin:/Users/dpogue/.rvm/gems/ruby-2.1.10/bin:/Users/dpogue/.rvm/gems/ruby-2.1.10@global/bin:/Users/dpogue/.rvm/rubies/ruby-2.1.10/bin:/Users/dpogue/.android/tools:/Users/dpogue/.android/platform-tools:/usr/local/opt/gnupg/libexec/gpgbin:/Users/dpogue/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dpogue/.rvm/bin:/Users/dpogue/.rvm/bin
46 verbose lifecycle ios-deploy@1.9.2~preinstall: CWD: /usr/local/lib/node_modules/ios-deploy
47 silly lifecycle ios-deploy@1.9.2~preinstall: Args: [ '-c', './src/scripts/check_reqs.js && xcodebuild' ]
48 silly lifecycle ios-deploy@1.9.2~preinstall: Returned: code: 126  signal: null
49 info lifecycle ios-deploy@1.9.2~preinstall: Failed to exec preinstall script
50 verbose unlock done using /Users/dpogue/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
51 verbose stack Error: ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
51 verbose stack Exit status 126
51 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at EventEmitter.emit (events.js:213:7)
51 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
51 verbose stack     at emitTwo (events.js:125:13)
51 verbose stack     at ChildProcess.emit (events.js:213:7)
51 verbose stack     at maybeClose (internal/child_process.js:927:16)
51 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
52 verbose pkgid ios-deploy@1.9.2
53 verbose cwd /Users/dpogue
54 verbose Darwin 16.7.0
55 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
56 verbose node v8.4.0
57 verbose npm  v5.4.0
58 error code ELIFECYCLE
59 error errno 126
60 error ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
60 error Exit status 126
61 error Failed at the ios-deploy@1.9.2 preinstall script.
61 error This is probably not a problem with npm. There is likely additional logging output above.
62 verbose exit [ 126, true ]
```

</details>

# Steps to reproduce the problem
Try to install ios-deploy globally with npm (v 5.4.0)

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType

  ```
  Software:
    System Software Overview:
      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: HW-41-Pripyat
      User Name: Darryl Pogue (dpogue)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 47 days 1:21
  ```

- [x] 2. ios-deploy -V
  Trying to install latest (1.9.2)

- [x] 3. xcodebuild -version
  ```
  Xcode 9.0
  Build version 9M214v
  ```

- [x] 4. xcode-select --print-path
  ```
  /Users/dpogue/Downloads/Xcode-beta.app/Contents/Developer
  ```

- [x] 5. gcc --version
  ```
  Configured with: --prefix=/Users/dpogue/Downloads/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
  Apple LLVM version 9.0.0 (clang-900.0.35)
  Target: x86_64-apple-darwin16.7.0
  Thread model: posix
  InstalledDir: /Users/dpogue/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  ```

- [x] 6. lldb --version
  ```
  lldb-900.0.46
    Swift-4.0
  ```

- [x] 7. npm --version
  ```
  5.4.0
  ```

**Comment by shazron** [comment]
Did you do use the additional flags specified in https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan-or-greater ?

**Comment by vovkasm** [comment]
This is npm issue: npm/npm#18324

**Comment by shazron** [comment]
Ouch. Probably have to revert to npm before the change or wait for the patch.

**Comment by dpogue** [comment]
Ah, thanks! I can close this (since it's not a ios-deploy problem) or leave it open for visibility?

**Comment by shazron** [comment]
Let's leave it open

**Comment by yipcma** [comment]
same issue...

**Comment by zarko-tg** [comment]
@yipcma npm 5.3.0 doesn't have the problem so I suggest you stay with it.

**Comment by zarko-tg** [comment]
npm@5.4.1 is out with the related fix on their side. @shazron can close this at will.
