### ISSUE TITLE
The following error occurred with CNPM install -g ios-deploy Error: Run "sh -c ./src/scripts/check_reqs.js && xcodebuild" error, exit code 1 at ChildProcess.proc.on.code 

### ISSUE THREAD

**Issue by fangyt** [phonegap/ios-deploy#324]
## MUST READ BEFORE YOU FILE (DELETE THIS SECTION BEFORE FILING)

Include the **command line arguments** you used for ios-deploy.

Operating system: MacOS High Sierra version: 10.13.2
Appium version: 1.7.2
Xcode Version: Version 9.2 (9C40b)

Question:
cnpm install -g ios-deploy
Downloading ios-deploy to /usr/local/lib/node_modules/ios-deploy_tmp
Copying /usr/local/lib/node_modules/ios-deploy_tmp/_ios-deploy@1.9.2@ios-deploy to /usr/local/lib/node_modules/ios-deploy
Installing ios-deploy's dependencies to /usr/local/lib/node_modules/ios-deploy/node_modules
scripts.preinstall ios-deploy@1.9.2  "./src/scripts/check_reqs.js && xcodebuild"
stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Install fail! Error: Run "sh -c ./src/scripts/check_reqs.js && xcodebuild" error, exit code 1
Error: Run "sh -c ./src/scripts/check_reqs.js && xcodebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npminstall version: 3.3.0
npminstall args: /usr/local/Cellar/node/9.3.0_1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/fangyongteng/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org -g ios-deploy

**Comment by fangyt** [comment]
I carried out this statement solves this problem: sudo xcode - select - switch/Applications/Xcode9.2 app/Contents/Developer
