### ISSUE TITLE
`npm install -g ios-deploy` stderr: xcode-select: error: tool 'xcodebuild' requires Xcode

### ISSUE THREAD

**Issue by bartonhammond** [phonegap/ios-deploy#327]
# Expected behavior
Successfully install ios-deploy

# Actual behavior.
```
barton@BMac ~ $ npm install -g ios-deploy

> ios-deploy@1.9.2 preinstall /usr/local/lib/node_modules/ios-deploy
> ./src/scripts/check_reqs.js && xcodebuild

stderr: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-deploy@1.9.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/barton/.npm/_logs/2018-02-03T21_25_40_065Z-debug.log
barton@BMac ~ $ 
```

# Steps to reproduce the problem
 `npm install -g ios-deploy`

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [ ] 1. system_profiler SPSoftwareDataType
```
barton@BMac ~ $ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.3 (17D47)
      Kernel Version: Darwin 17.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: BMac
      User Name: Barton Hammond (barton)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1:58
```
- [ ] 2. ios-deploy -
```
barton@BMac ~ $ ios-deploy
-bash: ios-deploy: command not found
```
- [ ] 3. xcodebuild -version
```
barton@BMac ~ $ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```
- [ ] 4. xcode-select --print-path
```
barton@BMac ~ $ xcode-select --print-path
/Library/Developer/CommandLineTools
```
- [ ] 5. gcc --version
```
barton@BMac ~ $ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
- [ ] 6. lldb --version
```
barton@BMac ~ $ lldb --version
lldb-900.0.64
  Swift-4.0
```
### Log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ios-deploy' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session ec5d85a5a2750a67
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/ios-deploy 359ms (from cache)
8 silly pacote tag manifest for ios-deploy@latest fetched in 435ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule ios-deploy@1.9.2 checking installable status
14 silly currentTree lib
15 silly idealTree lib
15 silly idealTree └── ios-deploy@1.9.2
16 silly install generateActionsToTake
17 silly diffTrees action count 1
18 silly diffTrees add ios-deploy@1.9.2
19 silly decomposeActions action count 8
20 silly decomposeActions fetch ios-deploy@1.9.2
21 silly decomposeActions extract ios-deploy@1.9.2
22 silly decomposeActions preinstall ios-deploy@1.9.2
23 silly decomposeActions build ios-deploy@1.9.2
24 silly decomposeActions install ios-deploy@1.9.2
25 silly decomposeActions postinstall ios-deploy@1.9.2
26 silly decomposeActions finalize ios-deploy@1.9.2
27 silly decomposeActions refresh-package-json ios-deploy@1.9.2
28 silly install executeActions
29 silly doSerial global-install 8
30 verbose correctMkdir /Users/barton/.npm/_locks correctMkdir not in flight; initializing
31 verbose lock using /Users/barton/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
32 silly doParallel extract 8
33 silly extract ios-deploy@1.9.2
34 silly doReverseSerial unbuild 8
35 silly doSerial remove 8
36 silly doSerial move 8
37 silly doSerial finalize 8
38 silly finalize /usr/local/lib/node_modules/ios-deploy
39 silly doParallel refresh-package-json 8
40 silly refresh-package-json /usr/local/lib/node_modules/ios-deploy
41 silly doParallel preinstall 8
42 silly preinstall ios-deploy@1.9.2
43 info lifecycle ios-deploy@1.9.2~preinstall: ios-deploy@1.9.2
44 verbose lifecycle ios-deploy@1.9.2~preinstall: unsafe-perm in lifecycle true
45 verbose lifecycle ios-deploy@1.9.2~preinstall: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/ios-deploy/node_modules/.bin:/usr/local/lib/node_modules/.bin:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/barton/tools/adt-bundle-mac-x86_64-20131030/sdk/tools:/Users/barton/tools/adt-bundle-mac-x86_64-20131030/sdk/platform-tools
46 verbose lifecycle ios-deploy@1.9.2~preinstall: CWD: /usr/local/lib/node_modules/ios-deploy
47 silly lifecycle ios-deploy@1.9.2~preinstall: Args: [ '-c', './src/scripts/check_reqs.js && xcodebuild' ]
48 silly lifecycle ios-deploy@1.9.2~preinstall: Returned: code: 1  signal: null
49 info lifecycle ios-deploy@1.9.2~preinstall: Failed to exec preinstall script
50 verbose unlock done using /Users/barton/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
51 verbose stack Error: ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
51 verbose stack Exit status 1
51 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
51 verbose stack     at emitTwo (events.js:126:13)
51 verbose stack     at EventEmitter.emit (events.js:214:7)
51 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
51 verbose stack     at emitTwo (events.js:126:13)
51 verbose stack     at ChildProcess.emit (events.js:214:7)
51 verbose stack     at maybeClose (internal/child_process.js:925:16)
51 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
52 verbose pkgid ios-deploy@1.9.2
53 verbose cwd /Users/barton
54 verbose Darwin 17.4.0
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ios-deploy"
56 verbose node v8.9.4
57 verbose npm  v5.6.0
58 error code ELIFECYCLE
59 error errno 1
60 error ios-deploy@1.9.2 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
60 error Exit status 1
61 error Failed at the ios-deploy@1.9.2 preinstall script.
61 error This is probably not a problem with npm. There is likely additional logging output above.
62 verbose exit [ 1, true ]
```

**Comment by surajpindoria** [comment]
Hi @bartonhammond,

Looking at the error messages it seem that you do not have Xcode installed on your machine. Could you try first installing that and then trying to get ios-deploy working.

**Comment by ErikAGriffin** [comment]
Hi, I am having the same issue, also on Mac OS 10.13.3

I can verify I have XCode installed, it's open in another window.  

Running xcodebuild --version also renders the error message `xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by bartonhammond** [comment]
@surajpindoria I upgraded my mac to 10.13.3 and installed XCode.  Here's what I see in AppStore:

![screen shot 2018-02-05 at 3 52 58 pm](https://user-images.githubusercontent.com/1282364/35830687-afce4e9e-0a8c-11e8-8f48-ae4032b8f7c0.png)

Am I missing something or need to run something else?

**Comment by ErikAGriffin** [comment]
@bartonhammond please see my comment

**Comment by bartonhammond** [comment]
@ErikAGriffin Thanks!  That did the trick.

**Comment by surajpindoria** [comment]
Thanks for the assist @ErikAGriffin!

**Comment by AnujMSG** [comment]
Hi @ErikAGriffin! bartonhammond surajpindoria

I am also stuck with same , Can you guys please let me know how to resolve this.

**Comment by AnujMSG** [comment]
surajpindoria

**Comment by AnujMSG** [comment]
Thanks ErikAGriffin

**Comment by pabloca88** [comment]
tried with @ErikAGriffin solutions but having the same outcome as before

**Comment by dhameer** [comment]
> tried with @ErikAGriffin solutions but having the same outcome as before

me too, my path is correct but still getting the error

**Comment by xchen1189** [comment]
A little follow-up, You are on OS X 10.11 El Capitan or greater, you may need to add the `--unsafe-perm=true` flag when running ` npm install

**Comment by canoas** [comment]
the steps to solve the issue
reset path to the xcode (nom CLI path) (@ErikAGriffin)
`
sudo xcode-select --reset
`
use the trick (@xchen1189) from https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan-or-greater
`
sudo npm install -g --unsafe-perm=true ios-deploy
`

**Comment by jerrychong25** [comment]
After using @ErikAGriffin method `sudo xcode-select --reset`, it will have another error code 65 ELIFECYCLE, as per below:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.1 preinstall: ./src/scripts/check_reqs.js && xcodebuild
npm ERR! Exit status 65
```

To complete solve this problem, need to use @xchen1189 method `sudo npm install -g --unsafe-perm=true ios-deploy`, then it will install ios-deploy successfully.

This solution is working as of 8th April 2019.

**Comment by Chaninat40** [comment]
Thank you @ErikAGriffin .

**Comment by PabloLMartinez** [comment]
> the steps to solve the issue
> reset path to the xcode (nom CLI path) (@ErikAGriffin)
> `sudo xcode-select --reset`
> use the trick (@xchen1189) from https://github.com/phonegap/ios-deploy#os-x-1011-el-capitan-or-greater
> `sudo npm install -g --unsafe-perm=true ios-deploy`

This works perfectly! I've been able to install it successfully! Thanks man

**Comment by aabdullahch** [comment]
Thank you @ErikAGriffin and @canoas
